### ISSUE TITLE
Roadmap to sass or ultility classes tailwind migrate in near future ?

### ISSUE THREAD

**Issue by mrtuvn** [breezefront/theme-frontend-breeze-blank#2]
Just question from my own! Not bug reports. I can't find any somewhere place for put my question

**Comment by ppeyman** [comment]
> Just question from my own! Not bug reports. I can't find any somewhere place for put my question

Hi Dear mrtuvn 
Please ask your question on [community](https://github.com/breezefront/community) discussion section 
thank you

**Comment by vovayatsyuk** [comment]
1. No plans for sass.
2. We have a few classes to simplify content creation in the admin panel: https://github.com/breezefront/theme-frontend-breeze-blank/blob/master/web/css/base/_helpers.less. But we cannot add all of the classes to the sources because it will increase CSS size.

**Comment by mrtuvn** [comment]
Thanks for all clarify!
