### ISSUE TITLE
Missing margins in Safari 13

### ISSUE THREAD

**Issue by fvlasie** [breezefront/theme-frontend-breeze-blank#5]
In Safari 13 (which a couple of my users still have) the spacing between elements is not working:

![Screen Shot 2023-06-13 at 23 03 07](https://github.com/breezefront/theme-frontend-breeze-blank/assets/33334298/1f86b4de-b897-40ef-b30b-818942cfa4bf)

Is there a fix that would work without breaking newer browsers?

**Comment by vovayatsyuk** [comment]
Sorry, we do not support outdated browsers.

**Comment by fvlasie** [comment]
I understand!
