### ISSUE TITLE
How can we incorporate Maganto Native Utilities?

### ISSUE THREAD

**Issue by IbrahimS2** [breezefront/theme-frontend-breeze-blank#7]
Various modules use Magento Utilities, how can we incorporate it to help with the third-party integration?

`https://github.com/magento/magento2/blob/ef81f5a2f8271ea529606fcb56898eed286d46b5/lib/web/css/source/lib/_utilities.less`

**Comment by vovayatsyuk** [comment]
Which of utils are you using?

**Comment by vovayatsyuk** [comment]
Here is how we added some of them: https://github.com/breezefront/theme-frontend-breeze-blank/blob/master/web/css/vendor/_luma.less

**Comment by IbrahimS2** [comment]
@vovayatsyuk Why not have the entire folder that we can use as reference when needed, `https://github.com/magento/magento2/tree/ef81f5a2f8271ea529606fcb56898eed286d46b5/lib/web/css/source/lib`

**Comment by vovayatsyuk** [comment]
Because it's a time and support when something goes wrong. We are not interested in adding everything from luma into breeze-blank.

You can add the utilities you need into your integration.
