### ISSUE TITLE
Microdata issue missing itemprop="image"

### ISSUE THREAD

**Issue by IvanDotsenko** [breezefront/theme-frontend-breeze-blank#9]
I found an issue with microdata, looks like you forgot to set up itemprop="image"

File to fix: 
vendor/swissup/module-breeze/view/frontend/templates/catalog/product/gallery.phtml

**Comment by vovayatsyuk** [comment]
Looks like it was replaced with `<link itemprop="...">` in 2.4.7: https://github.com/magento/magento2/commit/b9fb578ea6fb01e04b5ef588d6e7a00e4e26f2d0#diff-83580f32dcd07ecdb9d07c95f43e455f76a912cfe2b01a8fa20fe38a5b1fc6f3

gallery.phtml: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/view/frontend/templates/product/view/gallery.phtml#L42C5-L42C73

**Comment by vovayatsyuk** [comment]
Fixed: https://github.com/breezefront/module-breeze/commit/bcbeca2d45a1a9a044352bf7b701d9a084ea6725

Thank you for reporting!
